#!/bin/bash

apt-get update
apt-get install -y git make curl

mkdir /tmp/doploy
cd /tmp/doploy
curl -L# https://github.com/firstandthird/doploy/archive/master.tar.gz | tar zx --strip 1
make install
rm -rf /tmp/doploy
