#!/bin/bash

sudo apt-get update
sudo apt-get install tmux htop
curl -sSL https://get.docker.io/ubuntu/ | sudo sh

sudo rm -r /usr/local/bin
sudo ln -s /vagrant/bin /usr/local/bin
sudo mkdir -p /etc/shipment
